apiVersion: v1
kind: Service
metadata:
  name: cancer-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
    nodePort: 30080
  selector:
    app: cancer-app